name: origin_master_2024_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.5.4
  google_fonts: ^6.2.1
  sensors_plus: ^6.1.0
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  flutter_svg: ^2.0.11
  audioplayers: ^6.1.0
  dio: ^5.7.0
  sentry_flutter: ^8.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/music/
